-d /home/jordi/FPGAs/FPGA-Tang20k/GOWIN_HDL/test_placa/tangnano20k/impl/gwsynthesis/test_board.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst /home/jordi/FPGAs/FPGA-Tang20k/GOWIN_HDL/test_placa/tangnano20k/src/tld_test_board_tangnano20k.cst
-cfg /home/jordi/FPGAs/FPGA-Tang20k/GOWIN_HDL/test_placa/tangnano20k/impl/pnr/device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
